package GupangMSA.sellerservice.mock;

import GupangMSA.sellerservice.domain.product.SellerProduct;
import GupangMSA.sellerservice.domain.product.SellerProductUpdate;
import GupangMSA.sellerservice.exception.product.ProductDeleteException;
import GupangMSA.sellerservice.exception.product.ProductUpdateException;
import GupangMSA.sellerservice.infrastructure.SellerProductConnector;
import lombok.RequiredArgsConstructor;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

@RequiredArgsConstructor
public class FakeSellerProductConnector implements SellerProductConnector {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<SellerProduct> data = Collections.synchronizedList(new ArrayList<>());


    @Override
    public SellerProduct save(SellerProduct sellerProduct) {
        SellerProduct newSellerProduct = SellerProduct.builder()
                .id(autoGeneratedId.incrementAndGet())
                .sellerId(sellerProduct.getSellerId())
                .name(sellerProduct.getName())
                .price(sellerProduct.getPrice())
                .category(sellerProduct.getCategory())
                .description(sellerProduct.getDescription())
                .build();
        data.add(newSellerProduct);
        return newSellerProduct;
    }

    @Override
    public Optional<SellerProduct> findById(Long id) {
        return data.stream().filter(item ->
                Objects.equals(item.getId(), id)).findAny();
    }

    @Override
    public List<SellerProduct> findBySellerId(Long sellerId) {
        List<SellerProduct> sellerProducts = new ArrayList<>();
        for (SellerProduct sellerProduct : data) {
            if (Objects.equals(sellerProduct.getSellerId(), sellerId)) {
                sellerProducts.add(sellerProduct);
            }
        }
        return sellerProducts;
    }

    @Override
    public SellerProduct update(Long id, SellerProductUpdate sellerProductUpdate) {
        Optional<SellerProduct> optionalSellerProduct = data.stream().filter(item -> Objects.equals(item.getId(),
                id)).findAny();


        SellerProduct sellerProduct = optionalSellerProduct.orElseThrow(() ->
                new ProductUpdateException("product update failed"));


        SellerProduct updatedProduct = SellerProduct.builder()
                .id(sellerProduct.getId())
                .sellerId(sellerProduct.getSellerId())
                .name(sellerProductUpdate.getName())
                .price(sellerProductUpdate.getPrice())
                .category(sellerProduct.getCategory())
                .description(sellerProductUpdate.getDescription())
                .build();

        return updatedProduct;
    }

    @Override
    public void delete(Long productId) {
        Optional<SellerProduct> optionalSellerProduct = data.stream().filter(item ->
                Objects.equals(item.getId(), productId)).findAny();

        SellerProduct sellerProduct = optionalSellerProduct.orElseThrow(() ->
                new ProductDeleteException("product delete failed"));
        data.remove(sellerProduct);
    }
}
